params:
    # Minimum time (seconds) between scans for being attempted to be
    # aligned. Scans faster than this rate will be just silently ignored.
    min_time_between_scans: 0.0    # [seconds]
    # Minimum Euclidean distance (x,y,z) between keyframes inserted into
    # the map
    min_dist_xyz_between_keyframes: 2.0   # [meters]
    # Max pairings per layer (points, planes,...)
    max_correspondences_per_layer: 400
    # Minimum ICP "goodness" (in the range [0,1]) for a new KeyFrame to be accepted
    min_icp_goodness: 0.60        # range [0,1]
    # ditto, for loop-closures attempts to align
    min_icp_goodness_lc: 0.75     # range [0,1]
    # Voxel filter for edges:
    voxel_filter4edges_resolution: 2.0  # [meters]
    voxel_filter4edges_min_point_count: 10 # min. points count/voxel to accept
    voxel_filter4edges_min_point_spacing: 0.05   # [meters]
    voxel_filter4edges_decimation: 10
    voxel_filter4edges_max_e1_e0: 50
    voxel_filter4edges_min_e2_e1: 1
    # Voxel filter for planes:
    voxel_filter4planes_resolution: 3.0  # [meters]
    voxel_filter4planes_min_point_spacing: 0.0  # [meters]
    voxel_filter4planes_decimation: 30
    voxel_filter4planes_min_point_count: 30 # min. points count/voxel to accept
    voxel_filter4planes_min_e1_e0: 900
    voxel_filter4planes_min_e2_e0: 900
    #
    # min/max distance to check for match/loop closure between KFs:
    min_dist_to_matching: 5.0
    max_dist_to_matching: 20.0
    # Params for the MRPT ICP algoritm: See mrpt::slam::CICP for documentation
    # Case: WITH a good twist (velocity) model:
    icp_params_with_vel.maxIterations:     10     25
    icp_params_with_vel.thresholdDist:     0.60    0.50      # [meters]
    icp_params_with_vel.thresholdAng:      0.10    0.01     # [deg]
    icp_params_with_vel.useRobustKernel:   0       1
    # Case: WITHOUT a good twist (velocity) model:
    icp_params_without_vel.maxIterations:   5     25
    icp_params_without_vel.thresholdDist:   3.0    0.50  # [meters]
    icp_params_without_vel.thresholdAng:    2.0    0.01  # [deg]
    icp_params_without_vel.useRobustKernel: 0     1
    # Case: Loop closure
    loop_closure_montecarlo_samples: 5
    icp_params_loopclosure.maxIterations:   10    10     120
    icp_params_loopclosure.thresholdDist:   30.0   1.0     0.50  # [meters]
    icp_params_loopclosure.thresholdAng:     5.0   1.0     0.01  # [deg]
    icp_params_loopclosure.useRobustKernel:  0     0       1
    # -----------------------------------------------------
    # DEBUG: Save all ICP pairings as 3Dscene files, for visual inspection
    # Warning: this can consume a *huge* disk space
    #debug_save_lidar_odometry: true
    #debug_save_extra_edges: true
    debug_save_loop_closures: true
