params:
    # Minimum time (seconds) between scans for being attempted to be
    # aligned. Scans faster than this rate will be just silently ignored.
    min_time_between_scans: 0.0    # [seconds]
    # Minimum Euclidean distance (x,y,z) between keyframes inserted into
    # the map
    min_dist_xyz_between_keyframes: 1.0   # [meters]
    # If !=0, decimate point clouds so they do not have more than this number of points
    decimate_to_point_count: 100
    # Minimum ICP "goodness" (in the range [0,1]) for a new KeyFrame to be accepted
    min_icp_goodness: 0.50        # range [0,1]
    # ditto, for loop-closures attempts to align
    min_icp_goodness_lc: 0.75     # range [0,1]
    # Size (resolution) of the voxel filter
    voxel_filter_resolution: 2.0  # [meters]
    voxel_filter_min_point_count: 50 # min. points count/voxel to accept it
    # decimate as we filter by voxels (1=no decimation)
    full_pointcloud_decimation: 25
    voxel_filter_decimation: 5
    voxel_filter_max_e2_e0: 10
    voxel_filter_max_e1_e0: 10
    voxel_filter_min_e2_e0: 100
    voxel_filter_min_e1_e0: 10
    # min/max distance to check for match/loop closure between KFs:
    min_dist_to_matching: 5.0
    max_dist_to_matching: 20.0
    # Params for the MRPT ICP algoritm: See mrpt::slam::CICP for documentation
    # Case: WITH a good twist (velocity) model:
    icp_params_with_vel.maxIterations:  5  150
    icp_params_with_vel.thresholdDist: 1.0  0.5      # [meters]
    icp_params_with_vel.thresholdAng:  2.0  0.1     # [deg]
    # Case: WITHOUT a good twist (velocity) model:
    icp_params_without_vel.maxIterations:   5     150
    icp_params_without_vel.thresholdDist:   3.0   0.50  # [meters]
    icp_params_without_vel.thresholdAng:    2.0   0.10  # [deg]
    # Case: Loop closure
    icp_params_loopclosure.maxIterations: 10    30    140
    icp_params_loopclosure.thresholdDist: 30.0   1.0   0.50  # [meters]
    icp_params_loopclosure.thresholdAng:   5.0   1.0   0.01  # [deg]
    # -----------------------------------------------------
    # DEBUG: Save all ICP pairings as 3Dscene files, for visual inspection
    # Warning: this can consume a *huge* disk space
    #debug_save_lidar_odometry: true
    #debug_save_extra_edges: true
    debug_save_loop_closures: true
